# Generated by Django 4.1 on 2022-09-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_body_post_created_at_post_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
